variable "ENV" {}
variable "AWS_REGION" {}
variable "RESOURCES_PREFIX" {}
variable "CURRENT_ACCOUNT_ID" {}
variable "INFO_EMAIL" {}



variable "SIGN_UP_FUNCTION_ROLE_NAME" {}
variable "RESEND_CODE_FUNCTION_ROLE_NAME" {}
variable "LOGIN_FUNCTION_ROLE_NAME" {}
variable "VERIFY_ACCOUNT_FUNCTION_ROLE_NAME" {}
variable "CHANGE_PASSWORD_FUNCTION_ROLE_NAME" {}
variable "FORGOT_PASSWORD_FUNCTION_ROLE_NAME" {}
variable "CONFIRM_FORGOT_PASSWORD_FUNCTION_ROLE_NAME" {}
variable "CONFIRM_SIGNUP_FUNCTION_ROLE_NAME" {}